In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("severeinjury.csv",encoding="latin1") #encodin to read file correctly

In [ ]:
print(df.shape) # give us num of rows & column

(21578, 26)

In [ ]:
print(df.columns.tolist()) # to read column name and show them in list

['ID', 'UPA', 'EventDate', 'Employer', 'Address1', 'Address2', 'City', 'State', 'Zip', 'Latitude', 'Longitude', 'Primary NAICS', 'Hospitalized', 'Amputation', 'Inspection', 'Final Narrative', 'Nature', 'NatureTitle', 'Part of Body', 'Part of Body Title', 'Event', 'EventTitle', 'Source', 'SourceTitle', 'Secondary Source', 'Secondary Source Title']

In [ ]:
df.head()# to show first 5 rows

,ID,UPA,EventDate,Employer,Address1,Address2,City,State,Zip,Latitude,...,Nature,NatureTitle,Part of Body,Part of Body Title,Event,EventTitle,Source,SourceTitle,Secondary Source,Secondary Source Title
0,2015010015,931176,1/1/2015,FCI Otisville Federal Correctional Institution,Two Mile Drive,NaN,OTISVILLE,NEW YORK,10963.0,41.46,...,111,Fractures,513,Lower leg(s),1214,Injured by physical contact with person while ...,5721,Co-worker,5772.0,Inmate or detainee in custody
1,2015010016,930267,1/1/2015,Kalahari Manufacturing LLC,171 Progress Drive,NaN,LAKE DELTON,WISCONSIN,53940.0,43.59,...,1522,Second degree heat (thermal) burns,519,"Leg(s), n.e.c.",317,"Ignition of vapors, gases, or liquids",7261,"Welding, cutting, and blow torches",NaN,NaN
2,2015010018,929823,1/1/2015,Schneider National Bulk Carrier,420 CORAOPOLIS ROAD,NaN,CORAOPOLIS,PENNSYLVANIA,15108.0,40.49,...,10,"Traumatic injuries and disorders, unspecified",9999,Nonclassifiable,4331,Other fall to lower level less than 6 feet,8421,"Semi, tractor-trailer, tanker truck",741.0,Ladders-fixed
3,2015010019,929711,1/1/2015,PEPSI BOTTLING GROUP INC.,4541 HOUSTON AVE.,NaN,MACON,GEORGIA,31206.0,32.77,...,1972,"Soreness, pain, hurt-nonspecified injury",510,"Leg(s), unspecified",640,Caught in or compressed by equipment or object...,8623,Pallet jack-powered,8420.0,"Truck-motorized freight hauling and utility, u..."
4,2015010020,929642,1/1/2015,North American Pipe Corporation,210 South Arch Street,NaN,JANESVILLE,WISCONSIN,53545.0,42.67,...,111,Fractures,4429,"Finger(s), fingernail(s), n.e.c.",6411,Caught in running equipment or machinery durin...,350,"Metal, woodworking, and special material machi...",NaN,NaN

In [ ]:
df.info() # give information about table like type of data,presence ofnull,num of column & row

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21578 entries, 0 to 21577
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      21578 non-null  int64
 1   UPA                     21578 non-null  int64
 2   EventDate               21578 non-null  object
 3   Employer                21578 non-null  object
 4   Address1                21568 non-null  object
 5   Address2                1861 non-null   object
 6   City                    21569 non-null  object
 7   State                   21578 non-null  object
 8   Zip                     21567 non-null  float64
 9   Latitude                21487 non-null  float64
 10  Longitude               21487 non-null  float64
 11  Primary NAICS           21576 non-null  object
 12  Hospitalized            21578 non-null  float64
 13  Amputation              21576 non-null  float64
 14  Inspection              7822 non-null   float64
 15  Final Narrative         21578 non-null  object
 16  Nature                  21578 non-null  int64
 17  NatureTitle             21578 non-null  object
 18  Part of Body            21578 non-null  int64
 19  Part of Body Title      21578 non-null  object
 20  Event                   21578 non-null  int64
 21  EventTitle              21578 non-null  object
 22  Source                  21578 non-null  int64
 23  SourceTitle             21578 non-null  object
 24  Secondary Source        5812 non-null   float64
 25  Secondary Source Title  5812 non-null   object
dtypes: float64(7), int64(6), object(13)
memory usage: 4.3+ MB

In [ ]:
df.describe() # give me static analysis like max , min , count

,ID,UPA,Zip,Latitude,Longitude,Hospitalized,Amputation,Inspection,Nature,Part of Body,Event,Source,Secondary Source
count,2.157800e+04,2.157800e+04,21567.000000,21487.000000,21487.000000,21578.000000,21576.000000,7.822000e+03,21578.000000,21578.000000,21578.000000,21578.000000,5812.000000
mean,3.545288e+09,1.064256e+06,47502.167061,36.722735,-87.691200,0.807999,0.269837,1.122091e+06,886.975206,2282.536055,3905.397071,4811.297618,5210.936855
std,5.041577e+09,7.175081e+04,25034.209285,5.500293,11.132113,0.412055,0.451033,5.528449e+04,779.275403,2796.269288,2523.757451,2882.715191,3227.633387
min,2.015010e+09,8.927350e+05,802.000000,-15.780000,-170.710000,0.000000,0.000000,8.371470e+05,7.000000,6.000000,20.000000,10.000000,10.000000
25%,2.015075e+09,1.003217e+06,30316.500000,32.200000,-95.400000,1.000000,0.000000,1.077550e+06,111.000000,320.000000,642.000000,3230.000000,2214.000000
50%,2.016021e+09,1.060610e+06,45216.000000,38.770000,-87.660000,1.000000,0.000000,1.121268e+06,1311.000000,513.000000,4331.000000,4153.500000,4418.000000
75%,2.016088e+09,1.127405e+06,72127.000000,41.090000,-80.625000,1.000000,1.000000,1.170130e+06,1312.000000,4422.000000,6252.000000,7124.000000,8621.000000
max,2.016121e+10,1.219296e+06,99901.000000,61.290000,145.750000,3.000000,9.000000,1.231162e+06,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000

In [ ]:
print(df.isnull().sum())

ID                            0
UPA                           0
EventDate                     0
Employer                      0
Address1                     10
Address2                  19717
City                          9
State                         0
Zip                          11
Latitude                     91
Longitude                    91
Primary NAICS                 2
Hospitalized                  0
Amputation                    2
Inspection                13756
Final Narrative               0
Nature                        0
NatureTitle                   0
Part of Body                  0
Part of Body Title            0
Event                         0
EventTitle                    0
Source                        0
SourceTitle                   0
Secondary Source          15766
Secondary Source Title    15766
dtype: int64

In [ ]:
df['EventDate'] = pd.to_datetime(df['EventDate'], errors='coerce') # convert to date type

In [ ]:
df['Month'] = df['EventDate'].dt.month

In [ ]:
df['Year'] = df['EventDate'].dt.year

In [ ]:
print(df['Month'].value_counts().sort_index())

Month
1     2507
2     2350
3     1607
4     1557
5     1532
6     1752
7     1892
8     1915
9     1783
10    1655
11    1540
12    1488
Name: count, dtype: int64

In [ ]:
print(df['Year'].value_counts().sort_index())

Year
2015     9858
2016    10089
2017     1631
Name: count, dtype: int64

In [ ]:
# تصنيف الإصابات حسب خطورتها بناءً على كلمات في NatureTitle
severity_count = {"خطيرة": 0, "متوسطة": 0, "غير محدد": 0}

serious_keywords = ["Amputation", "Fracture", "Loss of consciousness"]

for nature in df['NatureTitle']:
    if pd.isna(nature):
        severity_count["غير محدد"] += 1
    elif any(word.lower() in str(nature).lower() for word in serious_keywords):
        severity_count["خطيرة"] += 1
    else:
        severity_count["متوسطة"] += 1

print(severity_count)

{'خطيرة': 12426, 'متوسطة': 9152, 'غير محدد': 0}